name: Publish to PowerShell Gallery

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PowerShellGet
        shell: pwsh
        run: |
          Install-Module PowerShellGet -Force -AllowClobber

      - name: Publish Module
        shell: pwsh
        run: |
          $apiKey = "${{ secrets.PSGALLERY_APIKEY }}"
          Publish-Module -Path ./ -NuGetApiKey $apiKey -Verbose
